name: milwaukeetool Auto Sign

on:
  schedule:
    - cron: '10 23 * * *'  # 北京时间每天早上7点10分执行（UTC时间23:10）
  workflow_dispatch:

jobs:
  sign:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Run Sign Script
      env:
        MILWAUKEETOOL_CLIENT_ID: ${{ secrets.MILWAUKEETOOL_CLIENT_ID }}
        MILWAUKEETOOL_TOKEN_LIST: ${{ secrets.MILWAUKEETOOL_TOKEN_LIST }}
      run: python .github/workflows/milwaukeetool-sign.py
