name: milwaukeetool Auto Sign

on:
  schedule:
    - cron: '10 1 * * *'  # 北京时间每天早上7点10分
  workflow_dispatch:

jobs:
  sign:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install requests
      run: pip install requests

    - name: Run Sign Script
      env:
        MILWAUKEETOOL_CLIENT_ID: ${{ secrets.MILWAUKEETOOL_CLIENT_ID }}
        MILWAUKEETOOL_TOKEN_LIST: ${{ secrets.MILWAUKEETOOL_TOKEN_LIST }}
      run: python .github/workflows/milwaukeetool-sign.py
